title: Yiming Bao's Homepage
page-top-title: Yiming Bao's Homepage
top-section-bg-text: Be the person who you want to be.
home-subtitle: Yiming Bao
copyright-text: '&copy; Jerry Yin 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
